### ISSUE TITLE
Can't control-click (right click) in Mac Safari

### ISSUE THREAD

**Issue by JohnOCFII** [chrishamm/DuetWebControl#165]
I upgraded from 2.0.0-RC6 to the release version 2.0.2 and once again can't right-click.  I realized that perhaps Control-Click on the Apple TrackPad was being treated differently than an actual right-click with a mouse.  I attached a USB mouse, and confirmed that the right mouse-click works fine, but that the Control-Click does not work.  The menu is displayed, but does not stay in view once either the Control button or the mouse pad click is released.  

This is with MacOS 10.14.6 on a 2018 15" MacBook Pro.

Same issue as #149 - but I didn't differentiate from a physical mouse vs. the control-click in that submission.

https://support.apple.com/en-us/HT207700

**Comment by chrishamm** [comment]
There is a dedicate event for right-clicks in JavaScript which is called "contextmenu". I don't have a MacBook so I cannot investigate what event is triggered when a right-click is initiated from a touchpad but it sounds to me like Safari doesn't behave like the standard suggests. Hence I won't address this any further.

Perhaps this extension will resolve your problem: https://apps.apple.com/us/app/right-click/id1364038646?mt=12 If it doesn't, you may want to try out Firefox or Chrome instead of Safari.
