### ISSUE TITLE
DWC only showing 43 files on G-Code files

### ISSUE THREAD

**Issue by PDBeal** [chrishamm/DuetWebControl#23]
On my Duet 0.8.5 with RepRapFirmware 1.16 (2016-11-08) (DC42) and DWC 1.13, the G-Code files section is only showing 43 gcode files.  On the PanelDue, it shows all the files for print.  If  delete some of the files from the DWC G-Code Files area, it still shows 43 files, but is now showing some of the newer files that were recently uploaded via DWC.

Is the 43 file limit for DWC intended despite the PanelDue being capable of showing all files?

The machine in question currently has 47 files in the gcodes folder viewing through the FTP client.

**Comment by chrishamm** [comment]
That isn't a bug in the web interface, it's an issue in the firmware. The reason you cannot view all the files at this time is because the Duet cannot reserve more RAM for a longer JSON/FTP response. That's why the output is truncated. As a temporary work-around I suggest you move some files to sub-directories on your SD card - you should be able to rearrange them via drag'n'drop on DWC.

I intend to fix this in the firmware in the future, but I have not had time for this yet and I still need to merge in dc42's changes from RRF 1.17 before I can look into that.
