### ISSUE TITLE
Consider relabelling "Active" to "Target" in Printer control Temp settings

### ISSUE THREAD

**Issue by BrianGilbert** [chrishamm/DuetWebControl#5]
I believe that "Target" would be a more accurate representation of what this setting is, the Current reading is probably closer to an "Active" temp.

**Comment by chrishamm** [comment]
I disagree, because you can set both active and standby temperatures for each heater. In detail, the active temperature becomes the target temperature only when the tool assigned to the heater is selected (i.e. when it's active), else the target temperature equals the standby temperature unless the heater is turned off. Also see http://reprap.org/wiki/G-code#G10:_Tool_Offset

If you're interested in the plain target temperatures, I suggest you refer to M105. My fork of the firmware reports the current vs. target temperature in this format: H0: [current]/[target] H1: ...
But I don't see the point in changing it on the web interface.
