### ISSUE TITLE
Mime type in post request

### ISSUE THREAD

**Issue by pacioc193** [chrishamm/DuetWebControl#82]
Hi man,

i've done a little java software that upload automatically the file by ur "api".

My problem is : the uploaded file have the mime type and other information :

Example : 

--qu8Wk6ZFv2E05MHNpKRQXRs_OXeAuJuIV
Content-Disposition: form-data; name="file"; filename="prova.gcode"
Content-Type: application/octet-stream

--qu8Wk6ZFv2E05MHNpKRQXRs_OXeAuJuIV--

Is there any way to remove it automatically from your website?

**Comment by chrishamm** [comment]
No, I will not do this. Perhaps you need to change your "code" to send a plain POST request instead of an x-form-multipart POST request - it is not difficult to do this even with a simple TCP connection.

The reason RepRapFirmware, and hence DWC, use simple POST requests instead of the more common multipart POST requests is because the first processor RepRapFirmware runs on, the SAM3X of the Duet 0.6/0.8.5, slowed down too much during uploads and only checking the amount of data received allowed a big speed improvement.
